create type "public"."institution_category" as enum ('university', 'ngo', 'government', 'other');

create type "public"."institution_funding_type" as enum ('public', 'private', 'mixed', 'other');

create table "public"."institutions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "abbreviation" character varying(10),
    "institution_category" institution_category not null,
    "funding_type" institution_funding_type not null,
    "address" text,
    "website_url" text,
    "image_url" text,
    "city_id" bigint not null
);


alter table "public"."institutions" enable row level security;

CREATE UNIQUE INDEX institutions_pkey ON public.institutions USING btree (id);

alter table "public"."institutions" add constraint "institutions_pkey" PRIMARY KEY using index "institutions_pkey";

alter table "public"."institutions" add constraint "institutions_cities_id_fkey" FOREIGN KEY (city_id) REFERENCES cities(id) ON UPDATE SET NULL ON DELETE SET NULL not valid;

alter table "public"."institutions" validate constraint "institutions_cities_id_fkey";

create policy "Enable select for authenticated users only"
on "public"."institutions"
as permissive
for select
to authenticated
using (true);