create table "public"."states" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "abbreviation" varchar(10),
    "country_id" bigint not null
);


alter table "public"."states" enable row level security;

CREATE UNIQUE INDEX states_pkey ON public.states USING btree (id);

alter table "public"."states" add constraint "states_pkey" PRIMARY KEY using index "states_pkey";

alter table "public"."states" add constraint "states_country_id_fkey" FOREIGN KEY (country_id) REFERENCES countries(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."states" validate constraint "states_country_id_fkey";

create policy "Enable select for authenticated users only"
on "public"."states"
as permissive
for select
to authenticated
using (true);