create table "public"."cities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" text not null,
    "state_id" bigint not null
);


alter table "public"."cities" enable row level security;

CREATE UNIQUE INDEX cities_pkey ON public.cities USING btree (id);

alter table "public"."cities" add constraint "cities_pkey" PRIMARY KEY using index "cities_pkey";

alter table "public"."cities" add constraint "cities_state_id_fkey" FOREIGN KEY (state_id) REFERENCES states(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cities" validate constraint "cities_state_id_fkey";

create policy "Enable select for authenticated users only"
on "public"."cities"
as permissive
for select
to authenticated
using (true);