create type "public"."continents" as enum ('Africa', 'Antarctica', 'Asia', 'Europe', 'Oceania', 'North America', 'South America');

create table "public"."countries" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "iso2" text not null,
    "iso3" text,
    "local_name" text,
    "continent" continents
);

alter table "public"."countries" enable row level security;

CREATE UNIQUE INDEX countries_pkey ON public.countries USING btree (id);

alter table "public"."countries" add constraint "countries_pkey" PRIMARY KEY using index "countries_pkey";

create policy "Enable select for authenticated users only"
on "public"."countries"
as permissive
for select
to authenticated
using (true);