create extension if not exists "pg_jsonschema" with schema "extensions";

create type "public"."education_level_type" as enum ('high_school', 'undergraduate', 'other');

create type "public"."gender_type" as enum ('male', 'female', 'non_binary', 'prefer_not_to_say');

create type "public"."onboarding_status_type" as enum ('not_started', 'in_progress', 'completed');

create table "public"."onboarding_profiles" (
    "id" bigint generated by default as identity not null,
    "city_id" bigint,
    "date_of_birth" date,
    "education_level" education_level_type,
    "field_of_study_id" bigint,
    "first_name" text,
    "gender" gender_type,
    "intended_field_of_study_id" bigint,
    "last_name" text,
    "user_id" uuid not null,
    "onboarding_data" jsonb not null default '{}'::jsonb,
    "status" onboarding_status_type not null default 'not_started'::onboarding_status_type
);

alter table "public"."onboarding_profiles" enable row level security;

CREATE UNIQUE INDEX onboarding_profiles_user_id_key ON public.onboarding_profiles USING btree (user_id);

alter table "public"."onboarding_profiles" add constraint "check_onboarding_data" CHECK (jsonb_matches_schema('{
        "type": "object",
        "properties": {
            "additional_notes": {
                "type": "string",
                "maxLength": 300
            },
            "graduation_year": {
                "type": "number"
            },
            "last_attended_institution": {
                "type": "string",
                "maxLength": 150
            }
        }
    }'::json, onboarding_data)) not valid;

alter table "public"."onboarding_profiles" validate constraint "check_onboarding_data";

alter table "public"."onboarding_profiles" add constraint "onboarding_profiles_city_id_fkey" FOREIGN KEY (city_id) REFERENCES cities(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."onboarding_profiles" validate constraint "onboarding_profiles_city_id_fkey";

alter table "public"."onboarding_profiles" add constraint "onboarding_profiles_field_of_study_id_fkey" FOREIGN KEY (field_of_study_id) REFERENCES fields_of_study(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."onboarding_profiles" validate constraint "onboarding_profiles_field_of_study_id_fkey";

alter table "public"."onboarding_profiles" add constraint "onboarding_profiles_intended_field_of_study_id_fkey" FOREIGN KEY (intended_field_of_study_id) REFERENCES fields_of_study(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."onboarding_profiles" validate constraint "onboarding_profiles_intended_field_of_study_id_fkey";

alter table "public"."onboarding_profiles" add constraint "onboarding_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."onboarding_profiles" validate constraint "onboarding_profiles_user_id_fkey";

alter table "public"."onboarding_profiles" add constraint "onboarding_profiles_user_id_key" UNIQUE using index "onboarding_profiles_user_id_key";

create policy "Enable insert for users based on user_id"
on "public"."onboarding_profiles"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable update for users based on user_id"
on "public"."onboarding_profiles"
as permissive
for update
to public
using (( SELECT (auth.uid() = onboarding_profiles.user_id)))
with check (( SELECT (auth.uid() = onboarding_profiles.user_id)));


create policy "Enable users to view their own data only"
on "public"."onboarding_profiles"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));