create table "public"."fields_of_study" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" character varying(255) not null
);


alter table "public"."fields_of_study" enable row level security;

CREATE UNIQUE INDEX fields_of_study_pkey ON public.fields_of_study USING btree (id);

alter table "public"."fields_of_study" add constraint "fields_of_study_pkey" PRIMARY KEY using index "fields_of_study_pkey";

create policy "Enable select for authenticated users only"
on "public"."fields_of_study"
as permissive
for select
to authenticated
using (true);