create table "public"."extracurricular_activities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "name" character varying(255) not null
);


alter table "public"."extracurricular_activities" enable row level security;

create table "public"."user_extracurricular_activities" (
    "user_id" uuid not null,
    "activity_id" bigint not null
);


alter table "public"."user_extracurricular_activities" enable row level security;

CREATE UNIQUE INDEX extracurricular_activities_pkey ON public.extracurricular_activities USING btree (id);

CREATE UNIQUE INDEX user_activity_pkey ON public.user_extracurricular_activities USING btree (user_id, activity_id);

alter table "public"."extracurricular_activities" add constraint "extracurricular_activities_pkey" PRIMARY KEY using index "extracurricular_activities_pkey";

alter table "public"."user_extracurricular_activities" add constraint "user_activity_pkey" PRIMARY KEY using index "user_activity_pkey";

alter table "public"."user_extracurricular_activities" add constraint "user_extracurricular_activities_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES extracurricular_activities(id) ON DELETE CASCADE not valid;

alter table "public"."user_extracurricular_activities" validate constraint "user_extracurricular_activities_activity_id_fkey";

alter table "public"."user_extracurricular_activities" add constraint "user_extracurricular_activities_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."user_extracurricular_activities" validate constraint "user_extracurricular_activities_user_id_fkey";

create policy "Enable select for authenticated users only"
on "public"."extracurricular_activities"
as permissive
for select
to authenticated
using (true);


create policy "Enable insert for users based on user_id"
on "public"."user_extracurricular_activities"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable users to view their own data only"
on "public"."user_extracurricular_activities"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));