create table "public"."match_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "improvement_notes" text,
    "match_relevance_rating" smallint not null,
    "match_result_id" bigint not null,
    "contact_permission" boolean not null
);

alter table "public"."match_feedback" enable row level security;

CREATE UNIQUE INDEX match_feedback_pkey ON public.match_feedback USING btree (id);

alter table "public"."match_feedback" add constraint "match_feedback_pkey" PRIMARY KEY using index "match_feedback_pkey";

alter table "public"."match_feedback" add constraint "match_feedback_match_relevance_rating_check" CHECK (((match_relevance_rating >= 1) AND (match_relevance_rating <= 5))) not valid;

alter table "public"."match_feedback" validate constraint "match_feedback_match_relevance_rating_check";

alter table "public"."match_feedback" add constraint "match_feedback_match_result_id_fkey" FOREIGN KEY (match_result_id) REFERENCES match_results(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."match_feedback" validate constraint "match_feedback_match_result_id_fkey";

create policy "Enable insert for users based on user id"
on "public"."match_feedback"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM (match_results mr
     JOIN onboarding_profiles op ON ((mr.onboarding_profile_id = op.id)))
  WHERE ((mr.id = match_feedback.match_result_id) AND (op.user_id = ( SELECT auth.uid() AS uid))))));

create policy "Enable users to view their own data only"
on "public"."match_feedback"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM (match_results mr
     JOIN onboarding_profiles op ON ((mr.onboarding_profile_id = op.id)))
  WHERE ((mr.id = match_feedback.match_result_id) AND (op.user_id = ( SELECT auth.uid() AS uid))))));