create table "public"."match_scholarships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "match_result_id" bigint not null,
    "scholarship_id" bigint not null
);

alter table "public"."match_scholarships" enable row level security;

CREATE UNIQUE INDEX match_scholarships_match_result_id_scholarship_id_key ON public.match_scholarships USING btree (match_result_id, scholarship_id);

CREATE UNIQUE INDEX match_scholarships_pkey ON public.match_scholarships USING btree (id);

alter table "public"."match_scholarships" add constraint "match_scholarships_pkey" PRIMARY KEY using index "match_scholarships_pkey";

alter table "public"."match_scholarships" add constraint "match_scholarships_match_result_id_fkey" FOREIGN KEY (match_result_id) REFERENCES match_results(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."match_scholarships" validate constraint "match_scholarships_match_result_id_fkey";

alter table "public"."match_scholarships" add constraint "match_scholarships_match_result_id_scholarship_id_key" UNIQUE using index "match_scholarships_match_result_id_scholarship_id_key";

alter table "public"."match_scholarships" add constraint "match_scholarships_scholarship_id_fkey" FOREIGN KEY (scholarship_id) REFERENCES scholarships(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."match_scholarships" validate constraint "match_scholarships_scholarship_id_fkey";

create policy "Enable insert for users based on user id"
on "public"."match_scholarships"
as permissive
for insert
to authenticated
with check ((EXISTS ( SELECT 1
   FROM (match_results mr
     JOIN onboarding_profiles op ON ((op.id = mr.onboarding_profile_id)))
  WHERE ((mr.id = match_scholarships.match_result_id) AND (op.user_id = ( SELECT auth.uid() AS uid))))));


create policy "Enable users to view their own data only"
on "public"."match_scholarships"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM (match_results mr
     JOIN onboarding_profiles op ON ((op.id = mr.onboarding_profile_id)))
  WHERE ((mr.id = match_scholarships.match_result_id) AND (op.user_id = ( SELECT auth.uid() AS uid))))));