create extension if not exists "vector" with schema "extensions";

create type "public"."scholarship_category" as enum ('complementary', 'tuition', 'other');

create table "public"."scholarships" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "content" text not null,
    "embedding" vector(1536) not null,
    "institution_id" bigint not null,
    "name" text not null,
    "scholarship_category" scholarship_category not null,
    "url" text not null
);


alter table "public"."scholarships" enable row level security;

CREATE UNIQUE INDEX scholarships_pkey ON public.scholarships USING btree (id);

alter table "public"."scholarships" add constraint "scholarships_pkey" PRIMARY KEY using index "scholarships_pkey";

alter table "public"."scholarships" add constraint "scholarships_institution_id_fkey" FOREIGN KEY (institution_id) REFERENCES institutions(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."scholarships" validate constraint "scholarships_institution_id_fkey";

create policy "Enable select for authenticated users only"
on "public"."scholarships"
as permissive
for select
to authenticated
using (true);